<a href="https://colab.research.google.com/github/aweeeaja/Machine-learning/blob/main/KMeans_Clustering_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Read Dataset

In [ ]:
ctg = pd.read_csv('Cardiotocographic_normalisasi.csv')
ctg

,LBE,LB,AC,FM,UC,ASTV,MSTV,ALTV,MLTV,DL,DS,DP,DR,AD,DE,LD,FS,SUSP,CLASS,NSP
0,0.259259,0.259259,0.000000,0.000000,0.000000,0.813333,0.044118,0.472527,0.047337,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.888889,2.0
1,0.481481,0.481481,0.153846,0.000000,0.173913,0.066667,0.279412,0.000000,0.205128,0.125,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556,1.0
2,0.500000,0.500000,0.076923,0.000000,0.217391,0.053333,0.279412,0.000000,0.264300,0.125,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556,1.0
3,0.518519,0.518519,0.076923,0.000000,0.260870,0.053333,0.323529,0.000000,0.453649,0.125,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556,1.0
4,0.481481,0.481481,0.153846,0.000000,0.217391,0.053333,0.323529,0.000000,0.392505,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.111111,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,0.629630,0.629630,0.000000,0.000000,0.260870,0.893333,0.000000,0.274725,0.142012,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0
2122,0.629630,0.629630,0.038462,0.000000,0.391304,0.880000,0.029412,0.241758,0.140039,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0
2123,0.629630,0.629630,0.038462,0.000000,0.304348,0.893333,0.029412,0.219780,0.120316,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0
2124,0.629630,0.629630,0.038462,0.000000,0.391304,0.880000,0.029412,0.296703,0.138067,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0
2125,0.666667,0.666667,0.038462,0.001773,0.217391,0.826667,0.029412,0.395604,0.098619,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0

In [ ]:
# Memilih Atribut kolom
x_train=ctg[['LBE','LB','AC','FM','UC','ASTV','MSTV','ALTV',
           'MLTV','DL','DS','DP','DR','AD','DE','LD','FS','SUSP','CLASS']]
x_train

,LBE,LB,AC,FM,UC,ASTV,MSTV,ALTV,MLTV,DL,DS,DP,DR,AD,DE,LD,FS,SUSP,CLASS
0,0.259259,0.259259,0.000000,0.000000,0.000000,0.813333,0.044118,0.472527,0.047337,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.888889
1,0.481481,0.481481,0.153846,0.000000,0.173913,0.066667,0.279412,0.000000,0.205128,0.125,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556
2,0.500000,0.500000,0.076923,0.000000,0.217391,0.053333,0.279412,0.000000,0.264300,0.125,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556
3,0.518519,0.518519,0.076923,0.000000,0.260870,0.053333,0.323529,0.000000,0.453649,0.125,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556
4,0.481481,0.481481,0.153846,0.000000,0.217391,0.053333,0.323529,0.000000,0.392505,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,0.629630,0.629630,0.000000,0.000000,0.260870,0.893333,0.000000,0.274725,0.142012,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444
2122,0.629630,0.629630,0.038462,0.000000,0.391304,0.880000,0.029412,0.241758,0.140039,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444
2123,0.629630,0.629630,0.038462,0.000000,0.304348,0.893333,0.029412,0.219780,0.120316,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444
2124,0.629630,0.629630,0.038462,0.000000,0.391304,0.880000,0.029412,0.296703,0.138067,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444
2125,0.666667,0.666667,0.038462,0.001773,0.217391,0.826667,0.029412,0.395604,0.098619,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

# Clustering

In [ ]:
from sklearn.cluster import KMeans
kmean = KMeans(n_clusters=3)
kmean

KMeans(n_clusters=3)

In [ ]:
# Hasil Clustering
y_cluster = kmean.fit_predict(x_train)
y_cluster

c:\ProgramData\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\ProgramData\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(

array([2, 0, 0, ..., 1, 1, 1])

In [ ]:
# Menambahkan kolom hasil Cluster pada dataset
ctg['Cluster']=y_cluster
ctg

,LBE,LB,AC,FM,UC,ASTV,MSTV,ALTV,MLTV,DL,...,DP,DR,AD,DE,LD,FS,SUSP,CLASS,NSP,Cluster
0,0.259259,0.259259,0.000000,0.000000,0.000000,0.813333,0.044118,0.472527,0.047337,0.000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.888889,2.0,2
1,0.481481,0.481481,0.153846,0.000000,0.173913,0.066667,0.279412,0.000000,0.205128,0.125,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556,1.0,0
2,0.500000,0.500000,0.076923,0.000000,0.217391,0.053333,0.279412,0.000000,0.264300,0.125,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556,1.0,0
3,0.518519,0.518519,0.076923,0.000000,0.260870,0.053333,0.323529,0.000000,0.453649,0.125,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.555556,1.0,0
4,0.481481,0.481481,0.153846,0.000000,0.217391,0.053333,0.323529,0.000000,0.392505,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.111111,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,0.629630,0.629630,0.000000,0.000000,0.260870,0.893333,0.000000,0.274725,0.142012,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0,1
2122,0.629630,0.629630,0.038462,0.000000,0.391304,0.880000,0.029412,0.241758,0.140039,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0,1
2123,0.629630,0.629630,0.038462,0.000000,0.304348,0.893333,0.029412,0.219780,0.120316,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0,1
2124,0.629630,0.629630,0.038462,0.000000,0.391304,0.880000,0.029412,0.296703,0.138067,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.444444,2.0,1
2125,0.666667,0.666667,0.038462,0.001773,0.217391,0.826667,0.029412,0.395604,0.098619,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,1